### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EagleAglow**
Version 3.2 uses 8 threads on my PC, not sure about the LINUX side.

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Brian(@EagleAglow),

CRAP!! Mea culpa !!
I read your message somewhere and completely forgot to correct that!!

Cheers,
Gus

**Comment by EagleAglow** [comment]
No worries, but I AM confused by the results.  My first attempt (1 thread) was about 16 minutes on my PC and 6 on the testbed).  My last version was about 2.5 minutes on my PC (8 threads), so I was hoping for the same time ratio.

**Comment by gcarreno** [comment]
Hey Brian(@EagleAglow),

Humm, that is suss AF, indeed!!

I'm running your binary with these switches: `-i [[input]]`, where `[[input]]` get's replaced by the input file.

Am I missing something here?

If not, I'm guessing that you're running your test in either Win32 or Win64.
A lot of people have told me that the code that comes out of the Linux compiler is a bit shit when compared with :scream: Win32.
I'm still baffled by the fact that some Delphi experts are touting the feats of the Win32 version when we're in a 64n world :shrug: 

We need to get to the bottom of this, nonetheless!!

Cheers,
Gus

**Comment by EagleAglow** [comment]
Right, my runs are in 64bit windows.  4 cores, Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz  with about 10GB free memory.

The only switch is that a command line without an output file uses STDOUT.

I was wondering if the compiler for LINUX disliked Ryzen architecture, but my ignorance is probably showing.

**Comment by gcarreno** [comment]
Hey Brian(@EagleAglow),

> I was wondering if the compiler for LINUX disliked Ryzen architecture, but my ignorance is probably showing.

Yours and mine!!
I have absolutely no clue what's going on with the Delphi compiler for Linux :shrug: 

I was quite hopeful that this would not be a thing, but alas, looks like we do have a bit of an issue with performance when coming from the Linux compiler.

Cheers,
Gus

**Pull request merged**
