### PR TITLE
Update - Revision 04, 2-3 mins faster than the previous one.

### PR DESCRIPTION
**Pull request by ikelaiah**
Hi @gcarreno , 

This is my revision 4. About 2-3 mins faster on my laptop.
Thank you.

Regards,
Iwan

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Iwan(@ikelaiah),

Just had a quick skim over your code and I don't see anything about the new rounding code.

Probably you missed the announcement.

It's present in the same section as before.
It's now quite simpler.

If I did missed it in your code, please forgive me. Quite at the end of my awake cycle.

Cheers,
Gus

**Comment by ikelaiah** [comment]
Oh no. I'm sorry, I missed that bit.
Let me fix it and get backnto you.

Thanks @gcarreno .

Regards,
Iwan

**Comment by gcarreno** [comment]
More than welcome Iwan !!

**Comment by ikelaiah** [comment]
Hi @gcarreno , I've implemented the simpler rounding as per the latest `README.md`.

The output is mathing `4256d19d3e134d79cc6f160d428a1d859ce961167bd01ca528daca8705163910`

- Iwan

**Comment by gcarreno** [comment]
Awesome sauce!!
Merging !!

**Pull request merged**
