### PR TITLE
introducing mORMot / abcz entry

### PR DESCRIPTION
**Pull request by synopse**
- please check the README.md information

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

This is an awesome entry!!
First of all it ticks some admin niceties:
- It drops the binary in the proper place( Just the name needs adjustment )
- It has a Release build mode
Thanks for that!!

I only ask 3 things:
- The first heading of the `README.md` should contain your name: Arnaud Bouchez
- The folder name for the entry should be named `abouchez`
- The binary should be named `abouchez`

Apart from that, this is a solid entry.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

Installed `mORMot2` from stable 2.2 release.

Now just waiting for your corrections.

Will add you to the `entries.json` file to make you entry part of the rotation.

Cheers,
Gus

**Comment by synopse** [comment]
Done as requested.

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

Awesome sauce, thanks !!

Merging and testing.

I'll post preliminary results on your discussion, that I'll create once I've got some data for it.

Cheers,
Gus

**Pull request merged**
