### PR TITLE
Ikelaiah Revision 02

### PR DESCRIPTION
**Pull request by ikelaiah**
Hi @gcarreno ,

I've applied the rounding as shown in the [1brc-ObjectPascal](https://github.com/gcarreno/1brc-ObjectPascal)'s README.md.

Many thanks.

-ikelaiah

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey IKel(@ikelaiah),

Have you also made sure the output has the `a5ac84593c0d387dc3cf581114bab15c58d822fa64821a71c2d46ed113aa3a93` hash?

Cheers,
Gus

**Comment by ikelaiah** [comment]
It is not matching. Let me fix it.
I'm sorry for the trouble.

**Comment by gcarreno** [comment]
Hey Iwan(@ikelaiah),

It's absolutely no trouble to me :smile: 

I just press a button :rofl: :people_hugging: 

Cheers,
Gus

**Comment by ikelaiah** [comment]
It is done @gcarreno !

The sha256 of the output of this revision is `db3d79d31b50daa8c03a1e4f2025029cb137f9971aa04129d8bca004795ae524`.
Improved algo by storing float as int64. 

It is around 16 mins on my i7 11th gen laptop.
From 21 mins -> 18 mins -> 16 mins (now).

Thank you,
Iwan

**Comment by gcarreno** [comment]
Hey Iwan(@ikelaiah),

If I'm not mistaken, both the `cmem` and `cthreads` units should only be used once, at the earliest place.

Having them on your program and on your unit is not advisable, I think.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Iwan(@ikelaiah),

Never mind, I'll do that myself.
It's not changing your code in any important part, so we good.

Cheers,
Gus

**Comment by ikelaiah** [comment]
Thanks for the correction @gcarreno .
Next time, I'll make sure `cmem` and `cthreads` to be declared only once.

I'll note this in my cookbook.

Thanks for merging my PR.

-Iwan

**Pull request merged**
