### PR TITLE
ikelaiah's entry to the 1 BRC. New - Initial commit.

### PR DESCRIPTION
**Pull request by ikelaiah**
# Introduction

This is ikelaiah's entry to the 1 BRC. 

First revision. Sequential approch.

## Checks

The 1 billion row for testing has the same `sha256sum` as per requirement; `ebad17b266ee9f5cb3d118531f197e6f68c9ab988abc5cb9506e6257e1a52ce6 `.

The first 10 row also matched the baseline requirement as [stated in the Discord](https://discord.com/channels/570025060312547359/896807098518732901/1217616456007815228).

Credits has been added to acknowledge contributions from others.

## Why use sequential approach?

My knowledge limitation in Free Pascal and concurrency at the moment.
Hoping to learn how to use concurrency before May 2024 for a better `time`.

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey @ikelaiah,

This is a solid entry!! Thanks!!

Just some things:
- The folder should be your first initial and you last name.
- The `README.md` file should have the first title be you first and last name.
- The `LICENSE` file is not needed since we already have it on the root folder.

Could you please make those changes?

Apart from that, this looks pretty good !!

Cheers,
Gus

**Comment by ikelaiah** [comment]
Thanks @gcarreno.
The folder in entries is my first initial and my last name. **I**wan **Kelaiah** -> **ikelaiah**

I'll modify the `README.md`, sorry I missed this one out.
Also, I'll remove the `LICENSE.md` as well.

**Comment by ikelaiah** [comment]
Hi @gcarreno , I made changes as requested.

- As for the folder name, it is already using my first name initial and last name.
- Updated the `README.md` to have the first title with first and last name.
- Removed the `LICENSE` file

Many thanks.

**Comment by gcarreno** [comment]
Hey @ikelaiah,

ARGHHH!!! Such a faux pas!!!

I'm really sorry about me messing your name thing up!!! :people_hugging: :heart: 

I think that makes it official and I'll merge it!!

Cheers,
Gus

**Comment by ikelaiah** [comment]
No probs @gcarreno.

Thanks for managing this 1BRC for Object Pascal.

Kudos to you.

**Comment by gcarreno** [comment]
Hey @ikelaiah,

> Thanks for managing this 1BRC for Object Pascal.

More than welcome!!

> Kudos to you.

Thanks !!

Cheers,
Gus

**Pull request merged**
