### PR TITLE
Fix bug in temp calc

### PR DESCRIPTION
**Pull request by lawson89**
Fix bug in temp calc
Move utility functions to own unit

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Richard(@lawson89),

According to the Lazarus Wiki, the unit `cmem` must come before `cthreads`.

Can you please amend?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Richard(@lawson89),

Looks like you dragged some rubbish files :smile: 

Can you please remove those from the PR?

Cheers,
Gus

**Comment by lawson89** [comment]
Thanks Gus!

**Comment by gcarreno** [comment]
> Thanks Gus!

More than Welcome!!

Welp, that's spot on, so I'm merging.

Will do all the necessary testing and posting of results once I sleep.

**Pull request merged**
