### PR TITLE
ghatem single-threaded entry

### PR DESCRIPTION
**Pull request by georges-hatem**

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey Georges(@georges-hatem),

There's still that `baseline.output` file that you let slip in.

Apart from that, the PR is good. Even with the correction to the param parsing. Which is very welcomed!!

Cheers,
Gus

**Comment by georges-hatem** [comment]
@gcarreno file removed.  I also tried to alter attributes in my subfolder so as to see the file diff as text (currently github shows it as binary somehow).
it will still display as text at your end, just not diffable

**Comment by gcarreno** [comment]
Hey Georges(@georges-hatem),

Do you feel that it's now good to merge?

Cheers,
Gus

**Comment by georges-hatem** [comment]
Yes, it's ready

**Pull request merged**
