### PR TITLE
Entry from 'EagleAglow"

### PR DESCRIPTION
**Pull request by EagleAglow**
First commit - please let me know what may be missing, or what needs to change to satisfy testing automation - Discord user: briar.on.fire

### CODE REVIEW

**Comment by gcarreno** [comment]
Hey @EagleAglow,

Can you please rename your folder with first initial and last name?
This also goes for the binary name that should be dropped on the `bin` folder under the project's root folder.
Also, the first section of the `README.md` should be your full name.

Like I mention on the `README.md`, if you don't want top use your own name, please choose a fictitious one like Peter Parker, etc...

Besides that, I think we good.

And welcome to the group !!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey @EagleAglow,

CRAP!!!
Completely forgot to mention that officially you should output to `STDOUT`, not a file.

This means that your `-o` switch should be optional, please.

Cheers,
Gus

**Comment by EagleAglow** [comment]
OK, please cancel this request - I'll try again after I make some changes to name and program.  

I'm really confused about the STDOUT thing as it applies to Windows/Delphi.  As far as I can tell, Windows mangles the console output so it is not the correct list.  I've noted discussion about using the DEBUG compiler directive to send the output to a file.

At this point, I think the program is supposed to use the '-i' parameter to get the input file and always send output to the console (even if it gets mangled).  An optional '-o' parameter can identify an output file.  Using a DEBUG compiler directive for anything is not required.  Or is it?

Also, is there some STDOUT other than Write and WriteLn?  I can grab the Windows handle for that, but LINUX would probably complain.

**Comment by gcarreno** [comment]
Hey @EagleAglow,

> OK, please cancel this request - I'll try again after I make some changes to name and program.

No need, just pile up the commits, then ping me on the Discords when you've made it good.

> I'm really confused about the STDOUT thing as it applies to Windows/Delphi. As far as I can tell, Windows mangles the console output so it is not the correct list. I've noted discussion about using the DEBUG compiler directive to send the output to a file.

Ultimately, this will be evaluated on my Linux box, so it doesn't really matter if it produces the correct output on Windows. What counts is what it outputs on Linux.

> At this point, I think the program is supposed to use the '-i' parameter to get the input file and always send output to the console (even if it gets mangled). An optional '-o' parameter can identify an output file. Using a DEBUG compiler directive for anything is not required. Or is it?

Correct on the `-i`.
Correct on the optional `-o`.
The Debug trick is for you to have a way to test on Windows.
By having it drop the output to a file on Debug only, you can `SHA256` it.

> Also, is there some STDOUT other than Write and WriteLn? I can grab the Windows handle for that, but LINUX would probably complain.

We're all using `WriteLn` for the output, and that will perform well on the Linux side.

Cheers,
Gus

**Pull request closed without merging**
